from __future__ import annotations

from typing import Any


REFERENCE_SOURCES: list[dict[str, Any]] = [
    {
        "source_code": "src_eu_cosing",
        "name": "EU CosIng",
        "kind": "regulatory-ingredient-database",
        "homepage_url": "https://single-market-economy.ec.europa.eu/sectors/cosmetics/cosmetic-ingredient-database_en",
        "license_name": "European Commission public information",
        "reliability": "official-regulatory-reference",
    },
    {
        "source_code": "src_cir",
        "name": "Cosmetic Ingredient Review",
        "kind": "expert-safety-review",
        "homepage_url": "https://cir-reports.cir-safety.org/",
        "license_name": "Public report index",
        "reliability": "expert-review-reference",
    },
    {
        "source_code": "src_fda_allergens",
        "name": "FDA Allergens in Cosmetics",
        "kind": "public-health-guidance",
        "homepage_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/allergens-cosmetics",
        "license_name": "US government public domain",
        "reliability": "official-public-health-reference",
    },
    {
        "source_code": "src_fda_hair_dyes",
        "name": "FDA Hair Dyes",
        "kind": "public-health-guidance",
        "homepage_url": "https://www.fda.gov/cosmetics/cosmetic-products/hair-dyes",
        "license_name": "US government public domain",
        "reliability": "official-public-health-reference",
    },
    {
        "source_code": "src_fda_formaldehyde_hair",
        "name": "FDA Formaldehyde in Hair Smoothing Products",
        "kind": "public-health-guidance",
        "homepage_url": "https://www.fda.gov/consumers/consumer-updates/formaldehyde-hair-smoothing-products-what-you-should-know",
        "license_name": "US government public domain",
        "reliability": "official-public-health-reference",
    },
    {
        "source_code": "src_fda_skin_lightening",
        "name": "FDA Skin Lightening Product Safety",
        "kind": "public-health-guidance",
        "homepage_url": "https://www.fda.gov/consumers/health-fraud-scams/skin-facts-what-you-need-know-about-skin-lightening-products",
        "license_name": "US government public domain",
        "reliability": "official-public-health-reference",
    },
    {
        "source_code": "src_fda_aha",
        "name": "FDA Alpha Hydroxy Acids",
        "kind": "public-health-guidance",
        "homepage_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/alpha-hydroxy-acids",
        "license_name": "US government public domain",
        "reliability": "official-public-health-reference",
    },
    {
        "source_code": "src_fda_bha",
        "name": "FDA Beta Hydroxy Acids",
        "kind": "public-health-guidance",
        "homepage_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/beta-hydroxy-acids",
        "license_name": "US government public domain",
        "reliability": "official-public-health-reference",
    },
    {
        "source_code": "src_sccs_mi",
        "name": "SCCS Methylisothiazolinone Opinion",
        "kind": "scientific-safety-opinion",
        "homepage_url": "https://health.ec.europa.eu/publications/methylisothiazolinone-mi-p94-submission-iii-sensitisation-only_en",
        "license_name": "European Commission public information",
        "reliability": "official-scientific-opinion",
    },
    {
        "source_code": "src_sccs_salicylic",
        "name": "SCCS Salicylic Acid Children's Exposure Opinion",
        "kind": "scientific-safety-opinion",
        "homepage_url": "https://health.ec.europa.eu/publications/sccs-opinion-salicylic-acid-cas-no-69-72-7-ec-no-200-712-3-childrens-exposure_en",
        "license_name": "European Commission public information",
        "reliability": "official-scientific-opinion",
    },
    {
        "source_code": "src_sccs_vitamin_a",
        "name": "SCCS Vitamin A Opinion",
        "kind": "scientific-safety-opinion",
        "homepage_url": "https://health.ec.europa.eu/publications/revision-scientific-opinion-sccs157616-vitamin-retinol-retinyl-acetate-retinyl-palmitate_en",
        "license_name": "European Commission public information",
        "reliability": "official-scientific-opinion",
    },
    {
        "source_code": "src_sccs_arbutin",
        "name": "SCCS Alpha-Arbutin and Beta-Arbutin Opinion",
        "kind": "scientific-safety-opinion",
        "homepage_url": "https://health.ec.europa.eu/publications/safety-alpha-arbutin-and-beta-arbutin-cosmetic-products_en",
        "license_name": "European Commission public information",
        "reliability": "official-scientific-opinion",
    },
    {
        "source_code": "src_sccs_resorcinol",
        "name": "SCCS Resorcinol Opinion",
        "kind": "scientific-safety-opinion",
        "homepage_url": "https://health.ec.europa.eu/publications/resorcinol_en",
        "license_name": "European Commission public information",
        "reliability": "official-scientific-opinion",
    },
    {
        "source_code": "src_aad_pregnancy_skin",
        "name": "American Academy of Dermatology Pregnancy Skin Care",
        "kind": "dermatology-guidance",
        "homepage_url": "https://www.aad.org/public/everyday-care/skin-care-secrets/routine/pregnancy-skin-care",
        "license_name": "Public medical guidance",
        "reliability": "medical-specialty-guidance",
    },
    {
        "source_code": "src_aad_retinoids",
        "name": "American Academy of Dermatology Retinoid Guidance",
        "kind": "dermatology-guidance",
        "homepage_url": "https://www.aad.org/public/everyday-care/skin-care-secrets/anti-aging/retinoid-retinol",
        "license_name": "Public medical guidance",
        "reliability": "medical-specialty-guidance",
    },
    {
        "source_code": "src_ema_retinoids",
        "name": "EMA Retinoid Pregnancy Prevention Measures",
        "kind": "medicine-safety-guidance",
        "homepage_url": "https://www.ema.europa.eu/en/news/updated-measures-pregnancy-prevention-during-retinoid-use",
        "license_name": "European Medicines Agency public information",
        "reliability": "official-medicine-safety-guidance",
    },
    {
        "source_code": "src_openfda_cosmetic_events",
        "name": "openFDA Cosmetic Adverse Events",
        "kind": "adverse-event-signal",
        "homepage_url": "https://open.fda.gov/apis/cosmetic/event/",
        "license_name": "Public domain / CC0",
        "reliability": "signal-not-causation",
    },
    {
        "source_code": "src_pubchem",
        "name": "PubChem",
        "kind": "chemical-database",
        "homepage_url": "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
        "license_name": "Public domain",
        "reliability": "chemical-reference",
    },
    {
        "source_code": "src_ifra",
        "name": "IFRA Standards Library",
        "kind": "fragrance-standard",
        "homepage_url": "https://ifrafragrance.org/standards-library",
        "license_name": "Public standards index",
        "reliability": "industry-safety-standard",
    },
]


FRAGRANCE_ALLERGENS = [
    "Amyl cinnamal",
    "Amylcinnamyl alcohol",
    "Anisyl alcohol",
    "Benzyl alcohol",
    "Benzyl benzoate",
    "Benzyl cinnamate",
    "Benzyl salicylate",
    "Cinnamyl alcohol",
    "Cinnamaldehyde",
    "Citral",
    "Citronellol",
    "Coumarin",
    "Eugenol",
    "Farnesol",
    "Geraniol",
    "Hexyl cinnamal",
    "Hexyl cinnamaldehyde",
    "Hydroxycitronellal",
    "Hydroxyisohexyl 3-cyclohexene carboxaldehyde",
    "HICC",
    "Lyral",
    "Isoeugenol",
    "Lilial",
    "d-Limonene",
    "Limonene",
    "Linalool",
    "Methyl 2-octynoate",
    "Gamma-Methylionone",
    "Oak moss extract",
    "Tree moss extract",
    "Fragrance",
    "Parfum",
    "Perfume",
    "Aroma",
]


TRUSTED_RISK_RULES: list[dict[str, Any]] = [
    {
        "ingredient_names": FRAGRANCE_ALLERGENS,
        "ingredient_name_patterns": ["fragrance", "parfum", "perfume", "aroma"],
        "source_code": "src_fda_allergens",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/allergens-cosmetics",
        "external_id": "fda-fragrance-allergens-profile",
        "title": "Fragrance allergen sensitivity",
        "summary": "FDA lists fragrance ingredients among common cosmetic allergens. People with fragrance allergy, fragrance sensitivity, eczema, or contact dermatitis may be more likely to react to disclosed fragrance allergens or fragrance mixtures.",
        "severity": "moderate",
        "severity_score": 3,
        "side_effects": [
            "itching",
            "rash",
            "redness",
            "allergic contact dermatitis",
            "eye or mouth irritation",
        ],
        "applies_to": {
            "skin_types": ["sensitive"],
            "sensitivities": ["fragrance", "perfume", "essential oils"],
            "allergies": ["fragrance", "perfume", "limonene", "linalool", "eugenol", "citral"],
            "conditions": ["eczema", "contact dermatitis", "rosacea"],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.82,
    },
    {
        "ingredient_names": ["Latex", "Natural Rubber Latex", "Natural rubber"],
        "ingredient_name_patterns": ["latex"],
        "source_code": "src_fda_allergens",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/allergens-cosmetics",
        "external_id": "fda-latex-allergy",
        "title": "Latex allergy warning",
        "summary": "FDA lists natural rubber/latex among common cosmetic allergen classes. Users with known latex allergy should avoid products disclosing latex or natural rubber ingredients.",
        "severity": "high",
        "severity_score": 4,
        "side_effects": ["hives", "itching", "rash", "wheezing", "anaphylaxis"],
        "applies_to": {"allergies": ["latex", "natural rubber"]},
        "evidence_kind": "official-guidance",
        "confidence_score": 0.86,
    },
    {
        "ingredient_names": ["Nickel", "Gold"],
        "ingredient_name_patterns": ["nickel", "gold"],
        "source_code": "src_fda_allergens",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/allergens-cosmetics",
        "external_id": "fda-metal-allergy",
        "title": "Metal allergen sensitivity",
        "summary": "FDA lists nickel and gold among metals that may appear as cosmetic allergens. Users with known metal allergies should treat disclosed nickel or gold as relevant.",
        "severity": "moderate",
        "severity_score": 3,
        "side_effects": ["itching", "rash", "redness", "allergic contact dermatitis"],
        "applies_to": {"allergies": ["nickel", "gold", "metal"], "sensitivities": ["metal"]},
        "evidence_kind": "official-guidance",
        "confidence_score": 0.78,
    },
    {
        "ingredient_names": [
            "Methylisothiazolinone",
            "Methylchloroisothiazolinone",
            "Methylisothiazolinone/Methylchloroisothiazolinone",
            "MI",
            "MIT",
            "CMIT",
        ],
        "source_code": "src_fda_allergens",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/allergens-cosmetics",
        "external_id": "fda-isothiazolinone-preservative-allergen",
        "title": "Isothiazolinone preservative sensitivity",
        "summary": "FDA lists methylisothiazolinone and methylchloroisothiazolinone as preservative allergens. These ingredients are relevant for users with preservative sensitivity or allergic contact dermatitis history.",
        "severity": "moderate",
        "severity_score": 3,
        "side_effects": ["itching", "rash", "redness", "allergic contact dermatitis"],
        "applies_to": {
            "skin_types": ["sensitive"],
            "sensitivities": ["preservatives", "methylisothiazolinone", "isothiazolinone"],
            "allergies": ["methylisothiazolinone", "methylchloroisothiazolinone", "mi", "cmit"],
            "conditions": ["eczema", "contact dermatitis"],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.84,
    },
    {
        "ingredient_names": ["Methylisothiazolinone", "Methylchloroisothiazolinone", "MI", "MIT", "CMIT"],
        "source_code": "src_sccs_mi",
        "source_url": "https://health.ec.europa.eu/publications/methylisothiazolinone-mi-p94-submission-iii-sensitisation-only_en",
        "external_id": "sccs-mi-leave-on-hair-context",
        "title": "Methylisothiazolinone concentration/context warning",
        "summary": "SCCS concluded that the submitted data did not support MI safety at 100 ppm in rinse-off products or leave-on hair products from the point of view of contact allergy induction. Product concentration is usually unavailable in open data, so this rule flags relevant product contexts for review.",
        "severity": "high",
        "severity_score": 4,
        "side_effects": ["allergic contact dermatitis", "itching", "rash", "redness"],
        "applies_to": {
            "always": True,
            "product_text_keywords": [
                "leave on",
                "leave-on",
                "lotion",
                "cream",
                "moisturizer",
                "serum",
                "wipe",
                "wipes",
                "hair",
            ],
        },
        "evidence_kind": "official-scientific-opinion",
        "confidence_score": 0.72,
    },
    {
        "ingredient_names": [
            "Formaldehyde",
            "Formalin",
            "Bronopol",
            "2-bromo-2-nitropropane-1,3-diol",
            "5-bromo-5-nitro-1,3-dioxane",
            "Diazolidinyl urea",
            "DMDM hydantoin",
            "Imidazolidinyl urea",
            "Sodium hydroxymethylglycinate",
            "Quaternium-15",
        ],
        "source_code": "src_fda_allergens",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/allergens-cosmetics",
        "external_id": "fda-formaldehyde-releasing-preservatives",
        "title": "Formaldehyde-releasing preservative sensitivity",
        "summary": "FDA lists formaldehyde and several formaldehyde-releasing preservatives among common cosmetic preservative allergens.",
        "severity": "moderate",
        "severity_score": 3,
        "side_effects": ["itching", "rash", "redness", "allergic contact dermatitis"],
        "applies_to": {
            "skin_types": ["sensitive"],
            "sensitivities": ["preservatives", "formaldehyde"],
            "allergies": ["formaldehyde", "bronopol", "dmdm hydantoin", "quaternium 15"],
            "conditions": ["eczema", "contact dermatitis"],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.84,
    },
    {
        "ingredient_names": ["Formaldehyde", "Formalin", "Methylene glycol", "Paraformaldehyde"],
        "source_code": "src_fda_formaldehyde_hair",
        "source_url": "https://www.fda.gov/consumers/consumer-updates/formaldehyde-hair-smoothing-products-what-you-should-know",
        "external_id": "fda-formaldehyde-hair-smoothing",
        "title": "Hair smoothing formaldehyde exposure",
        "summary": "FDA warns that many hair smoothing or straightening products can release formaldehyde gas during heat processing. This rule applies when formaldehyde-related ingredients appear in hair smoothing or straightening product metadata.",
        "severity": "critical",
        "severity_score": 5,
        "side_effects": [
            "eye irritation",
            "nose and throat irritation",
            "breathing problems",
            "sensitization reactions",
            "long-term cancer concern",
        ],
        "applies_to": {
            "always": True,
            "product_text_keywords": [
                "hair smoothing",
                "smoothing",
                "straightening",
                "straightener",
                "relaxer",
                "keratin treatment",
                "brazilian blowout",
            ],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.9,
    },
    {
        "ingredient_names": [
            "p-Phenylenediamine",
            "P-Phenylenediamine",
            "PPD",
            "Para Phenylenediamine",
            "Paraphenylenediamine",
        ],
        "source_code": "src_fda_hair_dyes",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-products/hair-dyes",
        "external_id": "fda-ppd-hair-dye-sensitizer",
        "title": "PPD hair dye allergy warning",
        "summary": "FDA identifies paraphenylenediamine (PPD) as a hair dye ingredient prominently implicated in allergic reactions and cross-sensitization.",
        "severity": "high",
        "severity_score": 4,
        "side_effects": ["skin irritation", "hair loss", "swelling", "allergic contact dermatitis"],
        "applies_to": {
            "skin_types": ["sensitive"],
            "scalp_types": ["sensitive"],
            "sensitivities": ["hair dye", "ppd"],
            "allergies": ["ppd", "p phenylenediamine", "paraphenylenediamine"],
            "conditions": ["eczema", "contact dermatitis"],
            "product_text_keywords": ["hair dye", "hair color", "hair colour", "colorant", "colourant"],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.88,
    },
    {
        "ingredient_names": ["p-Phenylenediamine", "P-Phenylenediamine", "PPD", "Coal tar"],
        "source_code": "src_fda_hair_dyes",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-products/hair-dyes",
        "external_id": "fda-eye-area-hair-dye-warning",
        "title": "Eye-area dye warning",
        "summary": "FDA states coal-tar hair dyes are not eyebrow or eyelash dyes, and no color additives are approved for dyeing eyebrows or eyelashes. This rule applies when hair dye ingredients appear with eyebrow, eyelash, or eye-area product metadata.",
        "severity": "critical",
        "severity_score": 5,
        "side_effects": ["eye injury", "severe irritation", "possible blindness"],
        "applies_to": {
            "always": True,
            "product_text_keywords": ["eyebrow", "eyelash", "lash", "brow", "eye area"],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.92,
    },
    {
        "ingredient_names": ["Resorcinol"],
        "source_code": "src_sccs_resorcinol",
        "source_url": "https://health.ec.europa.eu/publications/resorcinol_en",
        "external_id": "sccs-resorcinol-hair-dye-context",
        "title": "Resorcinol hair dye concentration context",
        "summary": "SCCS assessed resorcinol safety in oxidative hair dyes and related hair products at specified concentration limits. Because open product data usually lacks concentration, this rule flags hair dye contexts for users with hair dye sensitivity or dermatitis history.",
        "severity": "moderate",
        "severity_score": 3,
        "side_effects": ["skin irritation", "eye irritation", "rash"],
        "applies_to": {
            "sensitivities": ["hair dye"],
            "conditions": ["eczema", "contact dermatitis"],
            "product_text_keywords": ["hair dye", "hair color", "hair colour", "colorant", "colourant"],
        },
        "evidence_kind": "official-scientific-opinion",
        "confidence_score": 0.68,
    },
    {
        "ingredient_names": ["Glycolic Acid", "Lactic Acid", "Mandelic Acid", "Malic Acid", "Tartaric Acid"],
        "source_code": "src_fda_aha",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/alpha-hydroxy-acids",
        "external_id": "fda-aha-sun-sensitivity",
        "title": "AHA sun sensitivity warning",
        "summary": "FDA recommends sunburn-alert labeling for topically applied cosmetics containing alpha hydroxy acids because AHAs may increase skin sensitivity to the sun.",
        "severity": "low",
        "severity_score": 2,
        "side_effects": ["sun sensitivity", "sunburn", "stinging", "irritation"],
        "applies_to": {
            "always": True,
            "product_text_keywords": [
                "skin",
                "face",
                "serum",
                "peel",
                "cream",
                "lotion",
                "moisturizer",
                "exfoliant",
                "toner",
            ],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.78,
    },
    {
        "ingredient_names": ["Glycolic Acid", "Lactic Acid", "Mandelic Acid", "Malic Acid", "Tartaric Acid"],
        "source_code": "src_fda_aha",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/alpha-hydroxy-acids",
        "external_id": "fda-aha-sensitive-skin",
        "title": "AHA irritation potential for sensitive skin",
        "summary": "FDA notes AHAs may increase sun sensitivity; users with sensitive, rosacea-prone, or eczema-prone skin may need extra caution with exfoliating acid products.",
        "severity": "moderate",
        "severity_score": 3,
        "side_effects": ["stinging", "burning", "redness", "rash", "sun sensitivity"],
        "applies_to": {
            "skin_types": ["sensitive", "dry"],
            "conditions": ["eczema", "rosacea", "contact dermatitis"],
            "sensitivities": ["acids", "aha", "glycolic acid", "lactic acid"],
            "product_text_keywords": ["skin", "face", "serum", "peel", "cream", "exfoliant", "toner"],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.68,
    },
    {
        "ingredient_names": ["Salicylic Acid"],
        "source_code": "src_fda_bha",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/beta-hydroxy-acids",
        "external_id": "fda-bha-sun-irritation-warning",
        "title": "BHA irritation and sun protection warning",
        "summary": "FDA advises patch testing BHA-containing products, stopping use if irritation or prolonged stinging occurs, and using sun protection.",
        "severity": "low",
        "severity_score": 2,
        "side_effects": ["stinging", "irritation", "sun sensitivity", "dryness"],
        "applies_to": {
            "always": True,
            "product_text_keywords": [
                "skin",
                "face",
                "acne",
                "serum",
                "peel",
                "toner",
                "cream",
                "lotion",
                "cleanser",
            ],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.76,
    },
    {
        "ingredient_names": ["Salicylic Acid"],
        "source_code": "src_fda_bha",
        "source_url": "https://www.fda.gov/cosmetics/cosmetic-ingredients/beta-hydroxy-acids",
        "external_id": "fda-bha-children-avoidance",
        "title": "BHA child-use warning",
        "summary": "FDA advises avoiding BHA-containing products on infants and children. SCCS separately evaluated salicylic-acid children's exposure with concentration and category-specific limits.",
        "severity": "high",
        "severity_score": 4,
        "side_effects": ["irritation", "stinging", "systemic exposure concern"],
        "applies_to": {"age_band": ["infant", "baby", "child", "children", "toddler"]},
        "evidence_kind": "official-guidance",
        "confidence_score": 0.84,
    },
    {
        "ingredient_names": ["Salicylic Acid"],
        "source_code": "src_sccs_salicylic",
        "source_url": "https://health.ec.europa.eu/publications/sccs-opinion-salicylic-acid-cas-no-69-72-7-ec-no-200-712-3-childrens-exposure_en",
        "external_id": "sccs-salicylic-child-concentration-context",
        "title": "Salicylic acid child concentration context",
        "summary": "SCCS concluded salicylic acid safety for children depends on concentration and product category. Open product data often lacks concentration, so child profiles trigger a review warning when salicylic acid is present.",
        "severity": "moderate",
        "severity_score": 3,
        "side_effects": ["irritation", "stinging", "aggregate exposure concern"],
        "applies_to": {"age_band": ["child", "children", "kid", "toddler"]},
        "evidence_kind": "official-scientific-opinion",
        "confidence_score": 0.72,
    },
    {
        "ingredient_names": [
            "Retinol",
            "Retinal",
            "Retinaldehyde",
            "Retinyl Acetate",
            "Retinyl Palmitate",
            "Tretinoin",
            "Adapalene",
            "Tazarotene",
            "Isotretinoin",
        ],
        "source_code": "src_ema_retinoids",
        "source_url": "https://www.ema.europa.eu/en/news/updated-measures-pregnancy-prevention-during-retinoid-use",
        "external_id": "ema-topical-retinoids-pregnancy",
        "title": "Retinoid pregnancy precaution",
        "summary": "EMA states topical retinoids should not be used during pregnancy or by people planning to have a baby as a precaution. AAD pregnancy skin-care guidance also lists OTC retinol among ingredients to avoid during pregnancy.",
        "severity": "high",
        "severity_score": 4,
        "side_effects": ["pregnancy exposure concern", "skin irritation", "dryness"],
        "applies_to": {"pregnancy": ["true"], "lactation": ["true"]},
        "evidence_kind": "official-medicine-safety-guidance",
        "confidence_score": 0.86,
    },
    {
        "ingredient_names": [
            "Retinol",
            "Retinal",
            "Retinaldehyde",
            "Retinyl Acetate",
            "Retinyl Palmitate",
            "Tretinoin",
            "Adapalene",
            "Tazarotene",
        ],
        "source_code": "src_aad_retinoids",
        "source_url": "https://www.aad.org/public/everyday-care/skin-care-secrets/anti-aging/retinoid-retinol",
        "external_id": "aad-retinoid-sensitive-rosacea-dryness",
        "title": "Retinoid irritation potential",
        "summary": "AAD notes people with skin allergies or dryness may not be good candidates for retinoid products and that people with redness or inflammation should ask a dermatologist about rosacea-directed therapies.",
        "severity": "moderate",
        "severity_score": 3,
        "side_effects": ["dryness", "redness", "peeling", "irritation"],
        "applies_to": {
            "skin_types": ["dry", "sensitive"],
            "conditions": ["rosacea", "eczema", "contact dermatitis"],
            "sensitivities": ["retinoids", "retinol"],
        },
        "evidence_kind": "dermatology-guidance",
        "confidence_score": 0.74,
    },
    {
        "ingredient_names": ["Hydroquinone", "Mercury", "Mercurous Chloride", "Calomel"],
        "ingredient_name_patterns": ["hydroquinone", "mercury"],
        "source_code": "src_fda_skin_lightening",
        "source_url": "https://www.fda.gov/consumers/health-fraud-scams/fda-warns-consumers-skin-products-containing-mercury-andor-hydroquinone",
        "external_id": "fda-skin-lightening-hydroquinone-mercury",
        "title": "Skin-lightening hydroquinone or mercury warning",
        "summary": "FDA advises consumers not to use OTC skin-lightening products due to mercury and/or hydroquinone concerns. FDA reports serious and potentially permanent health problems from mercury exposure and serious skin problems from hydroquinone-containing skin-lightening products.",
        "severity": "critical",
        "severity_score": 5,
        "side_effects": [
            "skin rash",
            "facial swelling",
            "skin discoloration",
            "kidney damage concern",
            "neurological damage concern",
        ],
        "applies_to": {
            "always": True,
            "product_text_keywords": [
                "skin lightening",
                "lightening",
                "whitening",
                "bleaching",
                "brightening",
                "dark spot",
                "fading",
                "hyperpigmentation",
            ],
        },
        "evidence_kind": "official-guidance",
        "confidence_score": 0.92,
    },
    {
        "ingredient_names": ["Hydroquinone"],
        "source_code": "src_aad_pregnancy_skin",
        "source_url": "https://www.aad.org/public/everyday-care/skin-care-secrets/routine/pregnancy-skin-care",
        "external_id": "aad-pregnancy-hydroquinone",
        "title": "Hydroquinone pregnancy precaution",
        "summary": "AAD pregnancy skin-care guidance lists hydroquinone among ingredients to avoid during pregnancy.",
        "severity": "high",
        "severity_score": 4,
        "side_effects": ["pregnancy exposure concern", "skin irritation", "skin discoloration"],
        "applies_to": {"pregnancy": ["true"], "lactation": ["true"]},
        "evidence_kind": "dermatology-guidance",
        "confidence_score": 0.78,
    },
    {
        "ingredient_names": ["Alpha-Arbutin", "Beta-Arbutin", "Arbutin"],
        "source_code": "src_sccs_arbutin",
        "source_url": "https://health.ec.europa.eu/publications/safety-alpha-arbutin-and-beta-arbutin-cosmetic-products_en",
        "external_id": "sccs-arbutin-hydroquinone-trace-context",
        "title": "Arbutin concentration and hydroquinone trace context",
        "summary": "SCCS considers alpha-arbutin and beta-arbutin safe at specified product-category concentrations and says hydroquinone in formulations should remain as low as possible. Because open product data usually lacks concentration, skin-lightening products with arbutin are flagged for review rather than treated as automatically unsafe.",
        "severity": "low",
        "severity_score": 2,
        "side_effects": ["concentration unknown", "skin irritation"],
        "applies_to": {
            "always": True,
            "product_text_keywords": ["lightening", "whitening", "brightening", "dark spot", "hyperpigmentation"],
        },
        "evidence_kind": "official-scientific-opinion",
        "confidence_score": 0.62,
    },
]
